---
title: "Descarga de la red hidrográfica"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Descarga de la red hidrográfica}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r Madrid}
# install.packages("mapSpain", "sf")
limites_madrid <- mapSpain::esp_get_ccaa("Madrid", year = "2024",
                                        epsg = "4258", resolution = "01") |>
  sf::st_geometry() |>
  terra::vect()
```


```{r descarga_hidro}
# Modificar la carpeta destino a conveniencia.
destino <- "C:/imidra/hidro"

# Inspeccionemos las capas que contienen los archivos ".gpkg".
l1 <- sf::st_layers(file.path(destino, "IGR_HI_v1_ES020_Duero.gpkg"))
l2 <- sf::st_layers(file.path(destino, "IGR_HI_v1_ES030_Tajo.gpkg"))

# Juntas cuencas Tajo y Duero.
v1 <- sf::st_read(file.path(destino, "IGR_HI_v1_ES020_Duero.gpkg"),
                  layer = "hi_cauce_s_es020", quiet = TRUE)
v2 <- sf::st_read(file.path(destino, "IGR_HI_v1_ES030_Tajo.gpkg"),
                  layer = "hi_cauce_s_es030", quiet = TRUE)
hidro <- sf::st_geometry(rbind(v1, v2))
```

Transformamos "hidro" para que tenga el mismo sistema de referencia que el MDT.

```{r transforma_hidro}
carpeta_mdt <- "C:/imidra/mdt"
mdt <- terra::rast(file.path(carpeta_mdt, "mdt_madrid.tif"))
hidro <- sf::st_transform(hidro, crs = terra::crs(mdt))

sf::st_write(hidro, file.path(destino, "hidro_madrid.shp"),
             append = FALSE, quiet = TRUE)
```

Construimos un ráster de distancias tomando el MDT como referencia. Primero convertimos la red hidrológica en un ráster para acelerar los cálculos.

```{r distancia_hidro}
hidro <- hidro |> terra::vect()
hidro_raster <- terra::rasterize(hidro, mdt, fun = min, touches = TRUE)
distancia_hidro <- terra::distance(hidro_raster)
terra::writeRaster(distancia_hidro, file.path(destino, "distancia_hidro.tif"))
```
